const categories = {
  ai: "AI",
  server: "Servers",
  chips: "Chips",
  networking: "Networking",
  dataFlow: "Data Flow",
  audio: "Audio",
  effects: "Effects",
  web3: "Web3",
} as const

type ComponentMapEntry = {
  name: string
  description: string
  props: Record<string, string | string[]>
  tags: string[]
  category: string[]
}

export const componentMap: ComponentMapEntry[] = [
  {
    name: "ServerStack",
    description: "a stack of three server units with animated LED indicators that flicker and pulse",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      flicker: "boolean",
    },
    category: [categories.server],
    tags: [
      "server",
      "server stack",
      "server cluster",
      "datacenter",
      "cloud",
      "cloud server",
      "backend",
      "hosting",
      "infrastructure",
      "rack",
      "led",
      "status",
      "pulse",
      "animated",
    ],
  },
  {
    name: "GpuCluster",
    description: "a cluster of GPU chips arranged in a grid pattern with animated cooling fans and glowing effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      fanAnimation: "boolean",
    },
    category: [categories.ai],
    tags: [
      "gpu",
      "gpu cluster",
      "cluster",
      "ai",
      "artificial intelligence",
      "machine learning",
      "deep learning",
      "llm",
      "compute",
      "parallel computing",
      "training",
      "datacenter",
      "hardware",
      "animated",
    ],
  },
  {
    name: "GpuChip",
    description: "a single GPU chip with a grid of connection dots and animated stroke effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      float: "boolean",
    },
    category: [categories.chips],
    tags: [
      "gpu",
      "gpu chip",
      "processor",
      "graphics processor",
      "silicon",
      "chip",
      "hardware",
      "compute",
      "artificial intelligence",
      "machine learning",
      "animated",
    ],
  },
  {
    name: "ConnectCube",
    description: "a 3D isometric cube with connecting lines and animated beam effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      float: "boolean",
      floatDistance: "number",
      floatDelay: "number",
      beam: "boolean",
      magnetic: "boolean",
      ping: "boolean",
    },
    category: [categories.web3],
    tags: [
      "cube",
      "3d",
      "isometric",
      "blockchain",
      "web3",
      "crypto",
      "node",
      "connection",
      "network",
      "distributed",
      "beam",
      "animated",
    ],
  },
  {
    name: "ServerRack",
    description: "a rack containing multiple servers or routers. 2 cables like lines are beside the rack that indicate data or network flow",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      float: "boolean",
      beam: "boolean",
      beamStroke: ["number", "number"],
      magnetic: "boolean",
    },
    category: [categories.server],
    tags: [
      "server rack",
      "rack",
      "server",
      "router",
      "switch",
      "network",
      "networking",
      "datacenter",
      "cloud",
      "backend",
      "hosting",
      "data flow",
      "cable",
      "animated",
    ],
  },
  {
    name: "Gpu",
    description: "a single GPU chip with animated cooling fans and glowing effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      rotationDuration: "number",
    },
    category: [categories.chips],
    tags: [
      "gpu",
      "graphics card",
      "graphics processor",
      "accelerator",
      "ai",
      "machine learning",
      "deep learning",
      "processor",
      "fan",
      "hardware",
      "animated",
    ],
  },
  {
    name: "AudioChip",
    description: "a single audio chip with animated glow and floating effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      float: "boolean",
      animate: "boolean",
    },
    category: [categories.audio],
    tags: [
      "audio",
      "audio chip",
      "sound",
      "voice",
      "music",
      "processor",
      "signal processing",
      "hardware",
      "animated",
    ],
  },
  {
    name: "MicRipple",
    description: "a microphone with animated ripple effects and floating animation",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      ripple: "boolean",
      bounce: "boolean",
      float: "boolean",
      animate: "boolean",
    },
    category: [categories.audio],
    tags: [
      "microphone",
      "mic",
      "voice",
      "speech",
      "recording",
      "podcast",
      "wave",
      "ripple",
      "sound",
      "audio",
      "animated",
    ],
  },
  {
    name: "RadarScan",
    description: "a radar scanning animation with animated dots and lines",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      animation: "boolean",
    },
    category: [categories.networking],
    tags: [
      "radar",
      "scan",
      "scanner",
      "tracking",
      "detection",
      "monitoring",
      "signal",
      "network",
      "security",
      "animated",
    ],
  },
  {
    name: "FastCompress",
    description: "a fast compression animation with animated lines and stars",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      animation: "boolean",
      speed: "number",
    },
    category: [categories.effects],
    tags: [
      "compression",
      "compress",
      "zip",
      "archive",
      "optimize",
      "performance",
      "speed",
      "transfer",
      "data",
      "stream",
      "animated",
    ],
  },
  {
    name: "FastZap",
    description: "a fast zap animation with animated lines and gradients",
    props: {
      className: "string",
      color: "string",
      animate: "boolean",
      pulseDuration: "number",
      speedLineDuration: "number",
    },
    category: [categories.effects],
    tags: [
      "zap",
      "lightning",
      "electric",
      "energy",
      "flash",
      "speed",
      "power",
      "performance",
      "animated",
    ],
  },
  {
    name: "RoboBrain",
    description: "a robotic brain animation with animated radar and floating effects",
    props: {
      className: "string",
      colors: "Partial<Colors>",
      rgb: "boolean",
      cycleColors: "string[]",
      cycleDuration: "number",
      floatDuration: "number",
      floatAmplitude: "number",
      radarDuration: "number",
    },
    category: [categories.ai],
    tags: [
      "robot",
      "brain",
      "artificial intelligence",
      "ai",
      "machine learning",
      "deep learning",
      "neural network",
      "llm",
      "agent",
      "automation",
      "animated",
    ],
  },
]