/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'

const DocsSolanaTokensLazyRouteImport = createFileRoute('/docs/solana-tokens')()
const DocsServerStackLazyRouteImport = createFileRoute('/docs/server-stack')()
const DocsServerRackLazyRouteImport = createFileRoute('/docs/server-rack')()
const DocsRoboBrainLazyRouteImport = createFileRoute('/docs/robo-brain')()
const DocsRadarScanLazyRouteImport = createFileRoute('/docs/radar-scan')()
const DocsMicRippleLazyRouteImport = createFileRoute('/docs/mic-ripple')()
const DocsIsometricCameraLazyRouteImport = createFileRoute(
  '/docs/isometric-camera',
)()
const DocsGpuClusterLazyRouteImport = createFileRoute('/docs/gpu-cluster')()
const DocsGpuChipLazyRouteImport = createFileRoute('/docs/gpu-chip')()
const DocsGpuLazyRouteImport = createFileRoute('/docs/gpu')()
const DocsFolderLazyRouteImport = createFileRoute('/docs/folder')()
const DocsFastZapLazyRouteImport = createFileRoute('/docs/fast-zap')()
const DocsFastCompressLazyRouteImport = createFileRoute('/docs/fast-compress')()
const DocsConnectCubeLazyRouteImport = createFileRoute('/docs/connect-cube')()
const DocsClockLazyRouteImport = createFileRoute('/docs/clock')()
const DocsAudioChipLazyRouteImport = createFileRoute('/docs/audio-chip')()
const DocsArrowInCubicLatticeLazyRouteImport = createFileRoute(
  '/docs/arrow-in-cubic-lattice',
)()

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSolanaTokensLazyRoute = DocsSolanaTokensLazyRouteImport.update({
  id: '/solana-tokens',
  path: '/solana-tokens',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/solana-tokens.lazy').then((d) => d.Route),
)
const DocsServerStackLazyRoute = DocsServerStackLazyRouteImport.update({
  id: '/server-stack',
  path: '/server-stack',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/server-stack.lazy').then((d) => d.Route),
)
const DocsServerRackLazyRoute = DocsServerRackLazyRouteImport.update({
  id: '/server-rack',
  path: '/server-rack',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/server-rack.lazy').then((d) => d.Route),
)
const DocsRoboBrainLazyRoute = DocsRoboBrainLazyRouteImport.update({
  id: '/robo-brain',
  path: '/robo-brain',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/robo-brain.lazy').then((d) => d.Route),
)
const DocsRadarScanLazyRoute = DocsRadarScanLazyRouteImport.update({
  id: '/radar-scan',
  path: '/radar-scan',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/radar-scan.lazy').then((d) => d.Route),
)
const DocsMicRippleLazyRoute = DocsMicRippleLazyRouteImport.update({
  id: '/mic-ripple',
  path: '/mic-ripple',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/mic-ripple.lazy').then((d) => d.Route),
)
const DocsIsometricCameraLazyRoute = DocsIsometricCameraLazyRouteImport.update({
  id: '/isometric-camera',
  path: '/isometric-camera',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/isometric-camera.lazy').then((d) => d.Route),
)
const DocsGpuClusterLazyRoute = DocsGpuClusterLazyRouteImport.update({
  id: '/gpu-cluster',
  path: '/gpu-cluster',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/gpu-cluster.lazy').then((d) => d.Route),
)
const DocsGpuChipLazyRoute = DocsGpuChipLazyRouteImport.update({
  id: '/gpu-chip',
  path: '/gpu-chip',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() => import('./routes/docs/gpu-chip.lazy').then((d) => d.Route))
const DocsGpuLazyRoute = DocsGpuLazyRouteImport.update({
  id: '/gpu',
  path: '/gpu',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() => import('./routes/docs/gpu.lazy').then((d) => d.Route))
const DocsFolderLazyRoute = DocsFolderLazyRouteImport.update({
  id: '/folder',
  path: '/folder',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() => import('./routes/docs/folder.lazy').then((d) => d.Route))
const DocsFastZapLazyRoute = DocsFastZapLazyRouteImport.update({
  id: '/fast-zap',
  path: '/fast-zap',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() => import('./routes/docs/fast-zap.lazy').then((d) => d.Route))
const DocsFastCompressLazyRoute = DocsFastCompressLazyRouteImport.update({
  id: '/fast-compress',
  path: '/fast-compress',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/fast-compress.lazy').then((d) => d.Route),
)
const DocsConnectCubeLazyRoute = DocsConnectCubeLazyRouteImport.update({
  id: '/connect-cube',
  path: '/connect-cube',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/connect-cube.lazy').then((d) => d.Route),
)
const DocsClockLazyRoute = DocsClockLazyRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() => import('./routes/docs/clock.lazy').then((d) => d.Route))
const DocsAudioChipLazyRoute = DocsAudioChipLazyRouteImport.update({
  id: '/audio-chip',
  path: '/audio-chip',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/audio-chip.lazy').then((d) => d.Route),
)
const DocsArrowInCubicLatticeLazyRoute =
  DocsArrowInCubicLatticeLazyRouteImport.update({
    id: '/arrow-in-cubic-lattice',
    path: '/arrow-in-cubic-lattice',
    getParentRoute: () => DocsRouteRoute,
  } as any).lazy(() =>
    import('./routes/docs/arrow-in-cubic-lattice.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/test': typeof TestRoute
  '/docs/arrow-in-cubic-lattice': typeof DocsArrowInCubicLatticeLazyRoute
  '/docs/audio-chip': typeof DocsAudioChipLazyRoute
  '/docs/clock': typeof DocsClockLazyRoute
  '/docs/connect-cube': typeof DocsConnectCubeLazyRoute
  '/docs/fast-compress': typeof DocsFastCompressLazyRoute
  '/docs/fast-zap': typeof DocsFastZapLazyRoute
  '/docs/folder': typeof DocsFolderLazyRoute
  '/docs/gpu': typeof DocsGpuLazyRoute
  '/docs/gpu-chip': typeof DocsGpuChipLazyRoute
  '/docs/gpu-cluster': typeof DocsGpuClusterLazyRoute
  '/docs/isometric-camera': typeof DocsIsometricCameraLazyRoute
  '/docs/mic-ripple': typeof DocsMicRippleLazyRoute
  '/docs/radar-scan': typeof DocsRadarScanLazyRoute
  '/docs/robo-brain': typeof DocsRoboBrainLazyRoute
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
  '/docs/solana-tokens': typeof DocsSolanaTokensLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/test': typeof TestRoute
  '/docs/arrow-in-cubic-lattice': typeof DocsArrowInCubicLatticeLazyRoute
  '/docs/audio-chip': typeof DocsAudioChipLazyRoute
  '/docs/clock': typeof DocsClockLazyRoute
  '/docs/connect-cube': typeof DocsConnectCubeLazyRoute
  '/docs/fast-compress': typeof DocsFastCompressLazyRoute
  '/docs/fast-zap': typeof DocsFastZapLazyRoute
  '/docs/folder': typeof DocsFolderLazyRoute
  '/docs/gpu': typeof DocsGpuLazyRoute
  '/docs/gpu-chip': typeof DocsGpuChipLazyRoute
  '/docs/gpu-cluster': typeof DocsGpuClusterLazyRoute
  '/docs/isometric-camera': typeof DocsIsometricCameraLazyRoute
  '/docs/mic-ripple': typeof DocsMicRippleLazyRoute
  '/docs/radar-scan': typeof DocsRadarScanLazyRoute
  '/docs/robo-brain': typeof DocsRoboBrainLazyRoute
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
  '/docs/solana-tokens': typeof DocsSolanaTokensLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/test': typeof TestRoute
  '/docs/arrow-in-cubic-lattice': typeof DocsArrowInCubicLatticeLazyRoute
  '/docs/audio-chip': typeof DocsAudioChipLazyRoute
  '/docs/clock': typeof DocsClockLazyRoute
  '/docs/connect-cube': typeof DocsConnectCubeLazyRoute
  '/docs/fast-compress': typeof DocsFastCompressLazyRoute
  '/docs/fast-zap': typeof DocsFastZapLazyRoute
  '/docs/folder': typeof DocsFolderLazyRoute
  '/docs/gpu': typeof DocsGpuLazyRoute
  '/docs/gpu-chip': typeof DocsGpuChipLazyRoute
  '/docs/gpu-cluster': typeof DocsGpuClusterLazyRoute
  '/docs/isometric-camera': typeof DocsIsometricCameraLazyRoute
  '/docs/mic-ripple': typeof DocsMicRippleLazyRoute
  '/docs/radar-scan': typeof DocsRadarScanLazyRoute
  '/docs/robo-brain': typeof DocsRoboBrainLazyRoute
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
  '/docs/solana-tokens': typeof DocsSolanaTokensLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/test'
    | '/docs/arrow-in-cubic-lattice'
    | '/docs/audio-chip'
    | '/docs/clock'
    | '/docs/connect-cube'
    | '/docs/fast-compress'
    | '/docs/fast-zap'
    | '/docs/folder'
    | '/docs/gpu'
    | '/docs/gpu-chip'
    | '/docs/gpu-cluster'
    | '/docs/isometric-camera'
    | '/docs/mic-ripple'
    | '/docs/radar-scan'
    | '/docs/robo-brain'
    | '/docs/server-rack'
    | '/docs/server-stack'
    | '/docs/solana-tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/test'
    | '/docs/arrow-in-cubic-lattice'
    | '/docs/audio-chip'
    | '/docs/clock'
    | '/docs/connect-cube'
    | '/docs/fast-compress'
    | '/docs/fast-zap'
    | '/docs/folder'
    | '/docs/gpu'
    | '/docs/gpu-chip'
    | '/docs/gpu-cluster'
    | '/docs/isometric-camera'
    | '/docs/mic-ripple'
    | '/docs/radar-scan'
    | '/docs/robo-brain'
    | '/docs/server-rack'
    | '/docs/server-stack'
    | '/docs/solana-tokens'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/test'
    | '/docs/arrow-in-cubic-lattice'
    | '/docs/audio-chip'
    | '/docs/clock'
    | '/docs/connect-cube'
    | '/docs/fast-compress'
    | '/docs/fast-zap'
    | '/docs/folder'
    | '/docs/gpu'
    | '/docs/gpu-chip'
    | '/docs/gpu-cluster'
    | '/docs/isometric-camera'
    | '/docs/mic-ripple'
    | '/docs/radar-scan'
    | '/docs/robo-brain'
    | '/docs/server-rack'
    | '/docs/server-stack'
    | '/docs/solana-tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/solana-tokens': {
      id: '/docs/solana-tokens'
      path: '/solana-tokens'
      fullPath: '/docs/solana-tokens'
      preLoaderRoute: typeof DocsSolanaTokensLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/server-stack': {
      id: '/docs/server-stack'
      path: '/server-stack'
      fullPath: '/docs/server-stack'
      preLoaderRoute: typeof DocsServerStackLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/server-rack': {
      id: '/docs/server-rack'
      path: '/server-rack'
      fullPath: '/docs/server-rack'
      preLoaderRoute: typeof DocsServerRackLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/robo-brain': {
      id: '/docs/robo-brain'
      path: '/robo-brain'
      fullPath: '/docs/robo-brain'
      preLoaderRoute: typeof DocsRoboBrainLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/radar-scan': {
      id: '/docs/radar-scan'
      path: '/radar-scan'
      fullPath: '/docs/radar-scan'
      preLoaderRoute: typeof DocsRadarScanLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/mic-ripple': {
      id: '/docs/mic-ripple'
      path: '/mic-ripple'
      fullPath: '/docs/mic-ripple'
      preLoaderRoute: typeof DocsMicRippleLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/isometric-camera': {
      id: '/docs/isometric-camera'
      path: '/isometric-camera'
      fullPath: '/docs/isometric-camera'
      preLoaderRoute: typeof DocsIsometricCameraLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/gpu-cluster': {
      id: '/docs/gpu-cluster'
      path: '/gpu-cluster'
      fullPath: '/docs/gpu-cluster'
      preLoaderRoute: typeof DocsGpuClusterLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/gpu-chip': {
      id: '/docs/gpu-chip'
      path: '/gpu-chip'
      fullPath: '/docs/gpu-chip'
      preLoaderRoute: typeof DocsGpuChipLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/gpu': {
      id: '/docs/gpu'
      path: '/gpu'
      fullPath: '/docs/gpu'
      preLoaderRoute: typeof DocsGpuLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/folder': {
      id: '/docs/folder'
      path: '/folder'
      fullPath: '/docs/folder'
      preLoaderRoute: typeof DocsFolderLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/fast-zap': {
      id: '/docs/fast-zap'
      path: '/fast-zap'
      fullPath: '/docs/fast-zap'
      preLoaderRoute: typeof DocsFastZapLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/fast-compress': {
      id: '/docs/fast-compress'
      path: '/fast-compress'
      fullPath: '/docs/fast-compress'
      preLoaderRoute: typeof DocsFastCompressLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/connect-cube': {
      id: '/docs/connect-cube'
      path: '/connect-cube'
      fullPath: '/docs/connect-cube'
      preLoaderRoute: typeof DocsConnectCubeLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/clock': {
      id: '/docs/clock'
      path: '/clock'
      fullPath: '/docs/clock'
      preLoaderRoute: typeof DocsClockLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/audio-chip': {
      id: '/docs/audio-chip'
      path: '/audio-chip'
      fullPath: '/docs/audio-chip'
      preLoaderRoute: typeof DocsAudioChipLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/arrow-in-cubic-lattice': {
      id: '/docs/arrow-in-cubic-lattice'
      path: '/arrow-in-cubic-lattice'
      fullPath: '/docs/arrow-in-cubic-lattice'
      preLoaderRoute: typeof DocsArrowInCubicLatticeLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsArrowInCubicLatticeLazyRoute: typeof DocsArrowInCubicLatticeLazyRoute
  DocsAudioChipLazyRoute: typeof DocsAudioChipLazyRoute
  DocsClockLazyRoute: typeof DocsClockLazyRoute
  DocsConnectCubeLazyRoute: typeof DocsConnectCubeLazyRoute
  DocsFastCompressLazyRoute: typeof DocsFastCompressLazyRoute
  DocsFastZapLazyRoute: typeof DocsFastZapLazyRoute
  DocsFolderLazyRoute: typeof DocsFolderLazyRoute
  DocsGpuLazyRoute: typeof DocsGpuLazyRoute
  DocsGpuChipLazyRoute: typeof DocsGpuChipLazyRoute
  DocsGpuClusterLazyRoute: typeof DocsGpuClusterLazyRoute
  DocsIsometricCameraLazyRoute: typeof DocsIsometricCameraLazyRoute
  DocsMicRippleLazyRoute: typeof DocsMicRippleLazyRoute
  DocsRadarScanLazyRoute: typeof DocsRadarScanLazyRoute
  DocsRoboBrainLazyRoute: typeof DocsRoboBrainLazyRoute
  DocsServerRackLazyRoute: typeof DocsServerRackLazyRoute
  DocsServerStackLazyRoute: typeof DocsServerStackLazyRoute
  DocsSolanaTokensLazyRoute: typeof DocsSolanaTokensLazyRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsArrowInCubicLatticeLazyRoute: DocsArrowInCubicLatticeLazyRoute,
  DocsAudioChipLazyRoute: DocsAudioChipLazyRoute,
  DocsClockLazyRoute: DocsClockLazyRoute,
  DocsConnectCubeLazyRoute: DocsConnectCubeLazyRoute,
  DocsFastCompressLazyRoute: DocsFastCompressLazyRoute,
  DocsFastZapLazyRoute: DocsFastZapLazyRoute,
  DocsFolderLazyRoute: DocsFolderLazyRoute,
  DocsGpuLazyRoute: DocsGpuLazyRoute,
  DocsGpuChipLazyRoute: DocsGpuChipLazyRoute,
  DocsGpuClusterLazyRoute: DocsGpuClusterLazyRoute,
  DocsIsometricCameraLazyRoute: DocsIsometricCameraLazyRoute,
  DocsMicRippleLazyRoute: DocsMicRippleLazyRoute,
  DocsRadarScanLazyRoute: DocsRadarScanLazyRoute,
  DocsRoboBrainLazyRoute: DocsRoboBrainLazyRoute,
  DocsServerRackLazyRoute: DocsServerRackLazyRoute,
  DocsServerStackLazyRoute: DocsServerStackLazyRoute,
  DocsSolanaTokensLazyRoute: DocsSolanaTokensLazyRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
